### ISSUE TITLE
New Introhive Users Role assignments

### ISSUE THREAD

**Issue by tonyr-pm** [plantemoran-ms-d365/.github#8]

**Comment by tonyr-pm** [comment]
[Copy of Introhive User_New Users for July 2023.xlsx](https://github.com/plantemoran-ms-d365/.github/files/11789217/Copy.of.Introhive.User_New.Users.for.July.2023.xlsx)

**Comment by tonyr-pm** [comment]
@mrunnals  Am I only to add the 'Intorhive Form' and 'Intorhive User' to these accounts?

**Comment by mrunnals** [comment]
@tonyr-pm Yes, those are the two IH license roles for those users

**Comment by mrunnals** [comment]
@tonyr-pm  This is in progress, not up next, correct?

**Comment by tonyr-pm** [comment]
Hey Michele

I thought Courtenay changed it to ‘up next’ during our meeting on Monday because of the work items I was currently working on. I have since finished those and will start on this item tomorrow.

Best,

Tony Rodriguez | Senior Consultant | CRM Administrator | Technology Services
Plante Moran, 3000 Town Center, Suite 100, Southfield, MI 48075
Direct Dial: 248-223-3073 | Mobile: 219-781-2998
Plante Moran<http://www.plantemoran.com/pages/default.aspx> | Twitter<http://twitter.com/plantemoran> | Facebook<http://www.facebook.com/plantemoran> | LinkedIn<https://www.linkedin.com/company/plante-moran> | Learn from Leaders<https://www.plantemoran.com/explore-our-thinking/areas-of-focus/learn-from-leaders> | Manage Your Email Subscriptions <http://subscribe.plantemoran.com/>
We serve thousands of successful businesses and their leaders. Here are some of their best tips for success.

<https://www.plantemoran.com/explore-our-thinking/areas-of-focus/learn-from-leaders>
